### ISSUE TITLE
Adding Full Name of State

### ISSUE THREAD

**Issue by AColocho** [AColocho/us-states#1]
Location of module:
states -> states.py

Create a new class in the states.py module called States_Full_Name. Follow the format of States_Abbreviated, and write the name of each state in the order of States_Abbreviated. Example:

`
mid_atlantic = ['NJ', 'NY', 'PA']
`

Would turn to
`
mid_atlantic = ['New Jersey', 'New York', 'Pennsylvania']
`

**Comment by bjuspi** [comment]
Can you assign this to me ?
